### PR TITLE
Continuous kills from the same cursor position will augment clipboard

### PR DESCRIPTION
**Pull request by kyleboyle**
Killing at end of line will cut line break.
Killing multiple times from the same cursor position will append to clipboard.

### CODE REVIEW

**Comment by SebastianZaha** [comment]
Thank you for the contribution.

This does not work for me completely though. To reproduce, C-k 3 lines, then undo 3 times, C-k again, then paste.

I also should find some time to set up some tests I suppose to make contributions safer and easier :)

**Comment by kyleboyle** [comment]
Thanks, I just wanted to make sure you were interested in the functionality before I went any further. 

The reason why your scenario and a bunch of others produce incorrect clipboards is because it is not exiting "append mode" when I would like it to. I'd like to get a trigger on *any* action other than kill and exit append mode, but I'm not sure how to get the proper callbacks registered to do that. Do you have any suggestions?

**Comment by kyleboyle** [comment]
I think I have fixed the issue. Let me know what you think

**Comment by kyleboyle** [comment]
@SebastianZaha: feedback on this approach?

**Comment by SebastianZaha** [comment]
Hey, sorry for the delay. I have been on holiday a few weeks and now catching up on work. Will take a look and merge / release on the weekend!

**Comment by SebastianZaha** [comment]
This still does not work for me when doing multiple cuts and then a yank. I have created a test now for this, that fails.

**Comment by SebastianZaha** [comment]
I did not yet look at how to fix the issue, just tried to have some tests in place. I can also suggest a solution if you wish, just did not have too much time this morning.

**Comment by kyleboyle** [comment]
How are you running the tests? If I run them in via the debugger in vscode with no breakpoints, everything passes:

screen shot 2017-05-08 at 10 46 27 am

**Comment by SebastianZaha** [comment]
Hmm, works for me too in linux. Seems this is a windows-only problem, has something to do with the clipboard newline handling.

**Comment by SebastianZaha** [comment]
There also seems to be some weirdness when line wrapping is used. I'm currently looking closer at the kill method again. Will check back soon with findings.

**Comment by kyleboyle** [comment]
line wrap: looks like vscode.commands.executeCommand("cursorEndSelect") selects to the end of the line as displayed in the buffer, so it wouldn't select any wrapped characters belonging to the same line number.  I would expect the kill feature to kill all text on the same line number. I wonder how we can solve this.

**Comment by SebastianZaha** [comment]
I think I found a way to do this, by moving down a full line and then back to home.

I'm now looking at the clipboard eol thing, might be a bug in clipboardy actually, I'll try a test on that module for this case.

You had a comment in the code about "clipboard will strip off trailing newlines so we need to force append it", when was that happening to you?

**Comment by kyleboyle** [comment]
basically 

clip.writeSync("somestring\n") != clip.readSync()

clip.readSync() == "somestring"

I think readSync strips off the new line.. I can paste the clipboard elsewhere and it contains the new line.

**Comment by SebastianZaha** [comment]
Yeah, just found that out too. Seems to me an issue with the clipboard package. I will try to see if that is intended or a bug.

**Comment by SebastianZaha** [comment]
I submitted an issue to clipboardy, waiting to discuss the EOL handling with the npm package owner now.

**Comment by kyleboyle** [comment]
I raised an issue about the trailing new line: https://github.com/sindresorhus/clipboardy/issues/22

**Pull request merged**
